### ISSUE TITLE
Setup with Continue in VS Code

### ISSUE THREAD

**Issue by theonewolf** [svnscha/mcp-windbg#2]
@svnscha I'd like to use this MCP server with other LLMs, and I have tried setting an MCP block for use with Continue:

```yaml
mcpServers:
  - name: mcp_server_windbg

    type: stdio
    version: 0.0.1
    schema: v1
    command: cmd
    args:
      - /c
      - C:\Development\mcp-windbg\.venv\Scripts\python.exe
      - -m
      - mcp_server_windbg
    env:
      _NT_SYMBOL_PATH: "SRV*C:\\Symbols*https://msdl.microsoft.com/download/symbols"
  - name: mcp_server_windbg2
    command: cmd
    args:
      - /c
      - C:\Development\mcp-windbg\.venv\Scripts\python.exe
      - C:\Development\mcp-windbg\test.py
```

My second block will popup a GUI message window, but the first block never works.  Continue keeps claiming the server is "Not connected".

I do see zombie Python processes started every time I try to refresh / reload the MCP WinDbg server:

![Image](https://github.com/user-attachments/assets/aeaac9f4-bf64-427b-bff0-fddab95e1f12)

These are all started by Continue trying to run the `mcp_server_windbg` Python module.  Clearly the processes are persisting / running an infinite loop I think, but Continue / VS Code thinks things are "Not connected"

![Image](https://github.com/user-attachments/assets/8c848ee4-66c4-4e22-bf7e-93df4f97bc75)
